# Generated by Django 2.1.7 on 2019-03-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190306_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='default.png', upload_to=''),
        ),
    ]
